# Generated by Django 4.2.6 on 2023-10-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, unique=True, verbose_name='ID пользователя')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя')),
                ('pay_id', models.CharField(max_length=15, unique=True, verbose_name='Pay id (binance)')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('invite_link', models.URLField(blank=True, null=True)),
                ('referral_link', models.URLField(blank=True, null=True)),
                ('user_password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
            ],
            options={
                'verbose_name': 'Телеграмм Пользователь',
                'verbose_name_plural': 'Телеграмм Пользователи',
                'db_table': 'telegram_users',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='bot_ref.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bot_ref.user')),
            ],
            options={
                'unique_together': {('user', 'referral')},
            },
        ),
    ]
