# Generated by Django 4.2.6 on 2023-10-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Отправил деньги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
