# Generated by Django 4.2.6 on 2023-10-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0002_alter_user_invite_link_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_link',
        ),
        migrations.AddField(
            model_name='user',
            name='activated_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
