# Generated by Django 4.2.6 on 2023-10-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0003_remove_user_referral_link_user_activated_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated_link',
        ),
    ]
