# Generated by Django 4.2.6 on 2023-10-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0005_adminchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminChat',
        ),
    ]
