# Generated by Django 4.2.6 on 2023-10-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0006_delete_adminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_payments',
            field=models.IntegerField(default=0, verbose_name='Количество выплат'),
        ),
    ]
