# Generated by Django 4.2.6 on 2023-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0007_user_number_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_payments',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество выплат'),
        ),
    ]
