# Generated by Django 4.2.6 on 2023-11-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0009_user_referrer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referrer_id',
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='bot_ref.user', verbose_name='Кто пригласил'),
        ),
    ]
