# Generated by Django 4.2.6 on 2023-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0010_remove_user_referrer_id_user_referrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pay_id',
            new_name='pay_id',
        ),
    ]
