# Generated by Django 4.2.6 on 2023-12-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ref', '0012_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='bot_ref.user', verbose_name='Кто пригласил'),
        ),
    ]
